[theme]
primaryColor = "#00d4ff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#ffffff"
font = "sans serif"

[server]
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 100
headless = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[runner]
magicEnabled = false
installTracer = false

[client]
showErrorDetails = true
toolbarMode = "minimal"
