name: Test Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive  # Handle submodules if present
    
    - name: Test UI/API Dockerfile build
      run: |
        # Build the Docker image
        docker build -f Dockerfile -t nexa-api .
        
        # Run the container (now using FastAPI/uvicorn)
        docker run --rm -d -p 8000:8000 -e PORT=8000 --name test-api nexa-api
        
        # Wait for model loading and server startup
        echo "Waiting for server to start..."
        sleep 20
        
        # Show logs for debugging
        docker logs test-api
        
        # Test the health endpoint (FastAPI)
        curl -f http://localhost:8000/health || (echo "Health check failed!" && docker logs test-api && exit 1)
        
        # Stop the container
        docker stop test-api
        echo "Test passed!"
