name: Test Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Test UI Dockerfile build
      run: |
        docker build -f Dockerfile -t nexa-ui .
        docker run --rm -d -p 8501:8501 -e PORT=8501 --name test-ui nexa-ui
        sleep 10
        docker logs test-ui
        curl -f http://localhost:8501 || (docker logs test-ui && exit 1)
        docker stop test-ui
    
    - name: Test API Dockerfile build
      run: |
        docker build -f Dockerfile.api -t nexa-api .
        docker run --rm -d -p 8000:8000 -e PORT=8000 --name test-api nexa-api
        sleep 10
        docker logs test-api
        curl -f http://localhost:8000/health || (docker logs test-api && exit 1)
        docker stop test-api
